import polars as pl
from flowfile import node_designer as nd


class KmeansClusteringSettings(nd.NodeSettings):
    clustering: nd.Section = nd.Section(
        title="Clustering",
        description="Settings for K-means cluster",
        layout="horizontal",
        feature_columns=nd.ColumnSelector(
            label="Feature Columns",
            required=True,
            multiple=True,
            data_types=[
                "Numeric",
            ],
        ),
        n_clusters=nd.NumericInput(
            label="Number of clusters",
            default=3.0,
            min_value=2.0,
            max_value=20.0,
        ),
        cluster_column=nd.TextInput(
            label="Cluster column name",
            default="cluster",
            placeholder="",
        ),
        standardize=nd.ToggleSwitch(
            label="Standardize",
            default=True,
        ),
    )


class KmeansClustering(nd.CustomNodeBase):
    node_name: str = "kmeans clustering"
    node_category: str = "ML"
    node_icon: str = "kmeans.PNG"
    title: str = "kmeans clustering"
    intro: str = "Do a kmeans clustering with sklearn"
    author: str = "Edwardvaneechoud"
    version: str = "1.0.0"
    tags: list[str] = [
        "machine learning",
        "data-science",
    ]
    environment: str = "kernel"
    dependencies: list[str] = [
        "scikit-learn",
    ]
    example_inputs: list[dict[str, list]] = [
        {
            "customer_id": [
                "C001",
                "C002",
                "C003",
                "C004",
                "C005",
                "C006",
                "C007",
                "C008",
                "C009",
                "C010",
                "C011",
                "C012",
                "C013",
                "C014",
                "C015",
                "C016",
                "C017",
                "C018",
                "C019",
                "C020",
                "C021",
                "C022",
                "C023",
                "C024",
                "C025",
                "C026",
                "C027",
                "C028",
                "C029",
                "C030",
                "C031",
                "C032",
                "C033",
                "C034",
                "C035",
                "C036",
                "C037",
                "C038",
                "C039",
                "C040",
                "C041",
                "C042",
                "C043",
                "C044",
                "C045",
            ],
            "age": [
                26,
                45,
                47,
                57,
                46,
                53,
                50,
                44,
                58,
                59,
                43,
                48,
                26,
                62,
                58,
                52,
                56,
                23,
                45,
                56,
                24,
                46,
                60,
                24,
                41,
                28,
                25,
                56,
                50,
                24,
                23,
                19,
                20,
                64,
                45,
                46,
                22,
                26,
                26,
                62,
                27,
                48,
                57,
                58,
                63,
            ],
            "annual_income_k": [
                30.3,
                95.6,
                101.5,
                74,
                98,
                94.9,
                92.7,
                93.9,
                69.3,
                63.6,
                95.6,
                94.8,
                23.8,
                67.5,
                77.8,
                69.2,
                65.9,
                31.5,
                93.2,
                60.9,
                28.2,
                87.7,
                65,
                28.5,
                93,
                35.7,
                28.4,
                73.4,
                95.8,
                26.4,
                36.6,
                18.6,
                25.5,
                75.4,
                91.2,
                89.9,
                31.4,
                17,
                31.6,
                67.1,
                21.8,
                87.1,
                74.8,
                79.7,
                79.2,
            ],
            "spending_score": [
                34,
                81,
                86,
                9,
                92,
                84,
                79,
                80,
                28,
                11,
                89,
                83,
                25,
                28,
                20,
                16,
                22,
                33,
                80,
                20,
                36,
                76,
                18,
                33,
                90,
                34,
                39,
                24,
                80,
                37,
                40,
                41,
                31,
                23,
                76,
                92,
                37,
                37,
                35,
                24,
                29,
                79,
                8,
                28,
                22,
            ],
            "segment": [
                "budget",
                "premium",
                "premium",
                "saver",
                "premium",
                "premium",
                "premium",
                "premium",
                "saver",
                "saver",
                "premium",
                "premium",
                "budget",
                "saver",
                "saver",
                "saver",
                "saver",
                "budget",
                "premium",
                "saver",
                "budget",
                "premium",
                "saver",
                "budget",
                "premium",
                "budget",
                "budget",
                "saver",
                "premium",
                "budget",
                "budget",
                "budget",
                "budget",
                "saver",
                "premium",
                "premium",
                "budget",
                "budget",
                "budget",
                "saver",
                "budget",
                "premium",
                "saver",
                "saver",
                "saver",
            ],
        },
    ]
    example_settings: dict[str, dict] = {
        "clustering": {
            "feature_columns": [
                "age",
                "annual_income_k",
                "spending_score",
            ],
            "n_clusters": 3,
            "cluster_column": "cluster",
            "standardize": True,
        },
    }
    settings_schema: KmeansClusteringSettings = KmeansClusteringSettings()

    def process(self, *inputs: pl.LazyFrame) -> pl.LazyFrame:
        from sklearn.cluster import KMeans
        from sklearn.preprocessing import StandardScaler

        cfg = self.settings_schema.clustering
        feature_cols: list[str] = cfg.feature_columns.value     # list[str]

        k = int(cfg.n_clusters.value)                # a Numeric Input is always a float
        label_col = cfg.cluster_column.value

        df = inputs[0].collect()                     # sklearn needs eager data
        features = df.select(feature_cols).to_numpy()
        if cfg.standardize.value:
            features = StandardScaler().fit_transform(features)

        model = KMeans(n_clusters=k, n_init=10, random_state=42)
        labels = model.fit_predict(features)

        flowfile_ctx.log_info(
            f"Fitted {k} clusters over {len(feature_cols)} features and {df.height} rows"
        )
        return df.with_columns(pl.Series(label_col, labels))
